name: sail_app
description: a proxy client application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_icons: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  circular_check_box: ^1.0.2
  dio: ^4.0.6
  fluro: ^1.7.7
  shared_preferences: ^0.5.7+3
  webview_flutter: ^1.0.7
  provider: ^4.3.2
  flutter_screenutil: ^1.0.2
  flutter_swiper: ^1.1.6
  flutter_login: ^1.0.14
  flutter_easyrefresh: ^2.1.8
  intl: ^0.17.0
  flutter_tags: "^0.4.9+1"
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  path_provider: ^2.0.10
  crisp: ^0.3.1
  modal_bottom_sheet: ^2.0.1
  fluttertoast: ^8.0.9
  flutter_vpn: ^0.12.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
