name: Flutter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: Upload Artifact
    - uses: actions/upload-artifact@v3
      with:
        name: silversabres.${{ github.sha }}.ios
        path: build/ios/iphoneos/Runner.app
